name: raps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  http: ^0.13.5
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.0
  logger: ^1.1.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^10.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
